name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ozkankocakaplan/ziraatbayi-admin:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
          PORT: ${{ secrets.PORT }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key root@${{ secrets.HOST }} '
            docker pull ozkankocakaplan/ziraatbayi-admin:latest &&
            docker stop ziraatbayi-admin || true &&
            docker rm ziraatbayi-admin || true &&
            docker run -d -p 8000:${{ secrets.PORT }} --name ziraatbayi-admin -e REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }} ozkankocakaplan/ziraatbayi-admin:latest
          '
